### ISSUE TITLE
Need Add and Delete Button 

### ISSUE THREAD

**Issue by ghost** [hyunsjang/Tafe19S201#11]
Do we need send button , i delete that one and Add ADD and DELETE button at the button . Is this ok ??

**Comment by hyunsjang** [comment]
We do not need a send button, you are missing add and delete button at the bottom

**Comment by Roeche** [comment]
We can address this also @ TAFE.
The idea is to have at least 3 buttons. I.e. ADD, DELETE and UPDATE! (See my Issue recently opened).
