### ISSUE TITLE
Visual studio version issue

### ISSUE THREAD

**Issue by ghost** [hyunsjang/Tafe19S201#12]
I have used visual studio 2017 because i have 2017 in my laptop , i tried to download 2015 version but couldn't because 2015 version is not available now, So, what to do  now ?

**Comment by Roeche** [comment]
Hi Rojina, no worries. 
I understand what you are saying.
If it is definitely impossible to get VS2015, the only option that we will have is to use a computer that already has VS2015 installed.
We can use the code that you have already developed to create a fast brand new branch in one of TAFE's computer and from there upload to the remote repo.
We can address this ASAP @ TAFE.
Cheers!

**Comment by ghost** [comment]
Ya finally vs 2015 issue is ok now . Thanks everyone
