### ISSUE TITLE
Update option

### ISSUE THREAD

**Issue by Roeche** [hyunsjang/Tafe19S201#13]
@jasonwenlee , @hyunsjang , @RojiSharma 
Team: Remember not only developing code to create and delete records but also to update them.
Updating is different to creating or deleting. The idea is to amend the info of a current record of the database.

**Comment by jasonwenlee** [comment]
@roeche Noted. Amending personal feature to include Update and Clear functions

Edit: Update and Clear functions have been added. Last person to update their function with the features will close issue.

**Comment by hyunsjang** [comment]
Amending Shopping feature to include as well
