### ISSUE TITLE
Folder missing

### ISSUE THREAD

**Issue by Roeche** [hyunsjang/Tafe19S201#7]
@jasonwenlee mentioned that a folder was missing (InstaRichie) in the initial upload of the repo?
Team leader  (@hyunsjang) to verify and advice when repo ready to clone.

**Comment by jasonwenlee** [comment]
@Roeche Missing folder for InstaRichie has been uploaded. You can clone now :)
Closing issue.

**Comment by hyunsjang** [comment]
Uploaded the file in master.
